# Refs:
# - https://doc.rust-lang.org/cargo/reference/manifest.html
# - https://doc.rust-lang.org/cargo/guide/project-layout.html
# - https://doc.rust-lang.org/cargo/reference/cargo-targets.html

[package]
name = "webscreenshot"
version = "0.1.0"
authors = ["ğŸ·ğŸ› Lee Ball <lee.cat.ball@gmail.com>"]
edition = "2018"

[features]
cli-binary = ["clap"]

[lib]
name = "webscreenshotlib"

[[bin]]
name = "wss"
required-features = ["cli-binary"] 

[dependencies]
failure = "^0.1.8"
headless_chrome = "^0.9.0"
clap = { version = "2.33.1", optional = true }

[dev-dependencies]
more-asserts = "^0.2.1"