[package]
name = "shotweb"
version = "0.1.0"
authors = ["ğŸ·ğŸ› Lee Ball <lee.cat.ball@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "^0.1.8"
headless_chrome = "^0.9.0"
